-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])),
  old_values jsonb,
  new_values jsonb,
  utilisateur_id uuid,
  organisation_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  ip_address inet,
  user_agent text,
  employe_id uuid,
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id),
  CONSTRAINT audit_log_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id)
);
CREATE TABLE public.autres_equipements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  etat_des_lieux_id uuid,
  equipement text NOT NULL,
  etat_entree text,
  etat_sortie text,
  commentaires text,
  photos jsonb DEFAULT '[]'::jsonb,
  user_id uuid,
  employe_id uuid,
  CONSTRAINT autres_equipements_pkey PRIMARY KEY (id),
  CONSTRAINT autres_equipements_etat_des_lieux_id_fkey FOREIGN KEY (etat_des_lieux_id) REFERENCES public.etat_des_lieux(id),
  CONSTRAINT autres_equipements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT autres_equipements_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id)
);
CREATE TABLE public.cles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  etat_des_lieux_id uuid,
  type_cle_badge text,
  nombre integer,
  numero_cle text,
  commentaires text,
  photos jsonb DEFAULT '[]'::jsonb,
  user_id uuid,
  employe_id uuid,
  CONSTRAINT cles_pkey PRIMARY KEY (id),
  CONSTRAINT cles_etat_des_lieux_id_fkey FOREIGN KEY (etat_des_lieux_id) REFERENCES public.etat_des_lieux(id),
  CONSTRAINT cles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT cles_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id)
);
CREATE TABLE public.employes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  prenom text NOT NULL,
  nom text NOT NULL,
  email text,
  telephone text,
  fonction text,
  user_id uuid NOT NULL,
  actif boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by_auth_user_id uuid,
  updated_by_auth_user_id uuid,
  CONSTRAINT employes_pkey PRIMARY KEY (id),
  CONSTRAINT employes_auth_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT employes_created_by_auth_user_id_fkey FOREIGN KEY (created_by_auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT employes_updated_by_auth_user_id_fkey FOREIGN KEY (updated_by_auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.equipements_chauffage (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  etat_des_lieux_id uuid,
  chaudiere_etat text,
  chaudiere_date_dernier_entretien date,
  ballon_eau_chaude_etat text,
  radiateurs_nombre integer,
  radiateurs_etat text,
  thermostat_present boolean,
  thermostat_etat text,
  pompe_a_chaleur_present boolean,
  pompe_a_chaleur_etat text,
  commentaires text,
  photos jsonb DEFAULT '[]'::jsonb,
  user_id uuid,
  employe_id uuid,
  CONSTRAINT equipements_chauffage_pkey PRIMARY KEY (id),
  CONSTRAINT equipements_chauffage_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id),
  CONSTRAINT equipements_chauffage_etat_des_lieux_id_fkey FOREIGN KEY (etat_des_lieux_id) REFERENCES public.etat_des_lieux(id),
  CONSTRAINT equipements_chauffage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.equipements_energetiques (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  etat_des_lieux_id uuid,
  chauffage_type text,
  eau_chaude_type text,
  dpe_classe text,
  ges_classe text,
  date_dpe date,
  presence_panneaux_solaires boolean,
  type_isolation text,
  commentaires text,
  photos jsonb DEFAULT '[]'::jsonb,
  user_id uuid,
  employe_id uuid,
  CONSTRAINT equipements_energetiques_pkey PRIMARY KEY (id),
  CONSTRAINT equipements_energetiques_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id),
  CONSTRAINT equipements_energetiques_etat_des_lieux_id_fkey FOREIGN KEY (etat_des_lieux_id) REFERENCES public.etat_des_lieux(id),
  CONSTRAINT equipements_energetiques_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.etat_des_lieux (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  date_entree date,
  date_sortie date,
  adresse_bien text NOT NULL,
  statut text,
  type_etat_des_lieux text NOT NULL CHECK (type_etat_des_lieux = ANY (ARRAY['entree'::text, 'sortie'::text])),
  type_bien text NOT NULL CHECK (type_bien = ANY (ARRAY['studio'::text, 't2_t3'::text, 't4_t5'::text, 'inventaire_mobilier'::text, 'bureau'::text, 'local_commercial'::text, 'garage_box'::text, 'pieces_supplementaires'::text])),
  bailleur_nom text,
  bailleur_adresse text,
  locataire_nom text,
  locataire_adresse text,
  rendez_vous_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  photos jsonb DEFAULT '[]'::jsonb,
  travaux_a_faire boolean DEFAULT false,
  description_travaux text,
  created_by_auth_user_id uuid,
  updated_by_auth_user_id uuid,
  organisation_id uuid,
  visibilite text DEFAULT 'prive'::text CHECK (visibilite = ANY (ARRAY['prive'::text, 'organisation'::text, 'public'::text])),
  user_id uuid,
  organization_id uuid,
  signature_locataire text,
  signature_proprietaire_agent text,
  employe_id uuid,
  CONSTRAINT etat_des_lieux_pkey PRIMARY KEY (id),
  CONSTRAINT etat_des_lieux_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT etat_des_lieux_rendez_vous_id_fkey FOREIGN KEY (rendez_vous_id) REFERENCES public.rendez_vous(id),
  CONSTRAINT etat_des_lieux_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id),
  CONSTRAINT fk_etat_des_lieux_rendez_vous FOREIGN KEY (rendez_vous_id) REFERENCES public.rendez_vous(id),
  CONSTRAINT etat_des_lieux_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id),
  CONSTRAINT etat_des_lieux_created_by_auth_user_id_fkey FOREIGN KEY (created_by_auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT etat_des_lieux_updated_by_auth_user_id_fkey FOREIGN KEY (updated_by_auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.invitations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organisation_id uuid NOT NULL,
  email text NOT NULL,
  role text NOT NULL DEFAULT 'utilisateur'::text CHECK (role = ANY (ARRAY['admin_organisation'::text, 'utilisateur'::text])),
  invite_par_auth_user_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  accepted_at timestamp with time zone,
  accepted_by_auth_user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  statut text DEFAULT 'en_attente'::text CHECK (statut = ANY (ARRAY['en_attente'::text, 'accepte'::text, 'expire'::text, 'revoque'::text])),
  employe_id uuid,
  user_id uuid,
  CONSTRAINT invitations_pkey PRIMARY KEY (id),
  CONSTRAINT invitations_invite_par_auth_user_id_fkey FOREIGN KEY (invite_par_auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT invitations_accepted_by_auth_user_id_fkey FOREIGN KEY (accepted_by_auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT invitations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT invitations_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id),
  CONSTRAINT invitations_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  subscription_id uuid NOT NULL,
  stripe_invoice_id text NOT NULL UNIQUE,
  status text NOT NULL CHECK (status = ANY (ARRAY['draft'::text, 'open'::text, 'paid'::text, 'uncollectible'::text, 'void'::text])),
  amount_paid integer NOT NULL DEFAULT 0,
  amount_due integer NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'eur'::text,
  invoice_pdf text,
  invoice_number text,
  period_start timestamp with time zone,
  period_end timestamp with time zone,
  paid_at timestamp with time zone,
  due_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT invoices_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.organisations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  nom text NOT NULL,
  adresse text,
  telephone text,
  email text,
  siret text,
  logo_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  active boolean DEFAULT true,
  subscription_id uuid,
  user_id uuid,
  employe_id uuid,
  CONSTRAINT organisations_pkey PRIMARY KEY (id),
  CONSTRAINT organisations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT organisations_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT organisations_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id)
);
CREATE TABLE public.parties_privatives (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  etat_des_lieux_id uuid,
  type_partie text NOT NULL,
  etat_entree text,
  etat_sortie text,
  numero text,
  commentaires text,
  photos jsonb DEFAULT '[]'::jsonb,
  user_id uuid,
  employe_id uuid,
  CONSTRAINT parties_privatives_pkey PRIMARY KEY (id),
  CONSTRAINT parties_privatives_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id),
  CONSTRAINT parties_privatives_etat_des_lieux_id_fkey FOREIGN KEY (etat_des_lieux_id) REFERENCES public.etat_des_lieux(id),
  CONSTRAINT parties_privatives_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.permissions_partage (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  etat_des_lieux_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  permission text NOT NULL CHECK (permission = ANY (ARRAY['lecture'::text, 'ecriture'::text, 'admin'::text])),
  accorde_par_auth_user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  employe_id uuid,
  user_id uuid,
  CONSTRAINT permissions_partage_pkey PRIMARY KEY (id),
  CONSTRAINT permissions_partage_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT permissions_partage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT permissions_partage_etat_des_lieux_id_fkey FOREIGN KEY (etat_des_lieux_id) REFERENCES public.etat_des_lieux(id),
  CONSTRAINT permissions_partage_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id),
  CONSTRAINT permissions_partage_accorde_par_auth_user_id_fkey FOREIGN KEY (accorde_par_auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pieces (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  etat_des_lieux_id uuid,
  nom_piece text NOT NULL,
  revetements_sols text,
  murs_menuiseries text,
  plafond text,
  electricite_plomberie text,
  placards text,
  sanitaires text,
  menuiseries text,
  rangements text,
  baignoire_douche text,
  eviers_robinetterie text,
  chauffage_tuyauterie text,
  meubles_cuisine text,
  hotte text,
  plaque_cuisson text,
  commentaires text,
  photos jsonb DEFAULT '[]'::jsonb,
  user_id uuid,
  employe_id uuid,
  CONSTRAINT pieces_pkey PRIMARY KEY (id),
  CONSTRAINT pieces_etat_des_lieux_id_fkey FOREIGN KEY (etat_des_lieux_id) REFERENCES public.etat_des_lieux(id),
  CONSTRAINT pieces_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id),
  CONSTRAINT pieces_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.plan_limits (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  plan_id uuid NOT NULL,
  feature_name text NOT NULL,
  limit_value integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  CONSTRAINT plan_limits_pkey PRIMARY KEY (id),
  CONSTRAINT plan_limits_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id),
  CONSTRAINT plan_limits_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.releve_compteurs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  etat_des_lieux_id uuid,
  nom_ancien_occupant text,
  electricite_n_compteur text,
  electricite_h_pleines text,
  electricite_h_creuses text,
  gaz_naturel_n_compteur text,
  gaz_naturel_releve text,
  eau_chaude_m3 text,
  eau_froide_m3 text,
  photos jsonb DEFAULT '[]'::jsonb,
  user_id uuid,
  employe_id uuid,
  CONSTRAINT releve_compteurs_pkey PRIMARY KEY (id),
  CONSTRAINT releve_compteurs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT releve_compteurs_etat_des_lieux_id_fkey FOREIGN KEY (etat_des_lieux_id) REFERENCES public.etat_des_lieux(id),
  CONSTRAINT releve_compteurs_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id)
);
CREATE TABLE public.rendez_vous (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  date date NOT NULL,
  heure time without time zone NOT NULL,
  duree text,
  description text,
  adresse text NOT NULL,
  code_postal text NOT NULL,
  ville text NOT NULL,
  latitude double precision,
  longitude double precision,
  nom_contact text NOT NULL,
  telephone_contact text NOT NULL,
  email_contact text NOT NULL,
  note_personnelle text,
  type_etat_des_lieux text,
  type_bien text,
  created_at timestamp with time zone DEFAULT now(),
  statut text DEFAULT 'planifie'::text CHECK (statut = ANY (ARRAY['planifie'::text, 'realise'::text, 'annule'::text, 'reporte'::text])),
  etat_des_lieux_id uuid,
  photos jsonb DEFAULT '[]'::jsonb,
  created_by_auth_user_id uuid,
  updated_by_auth_user_id uuid,
  organisation_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  organization_id uuid,
  employe_id uuid,
  CONSTRAINT rendez_vous_pkey PRIMARY KEY (id),
  CONSTRAINT rendez_vous_created_by_auth_user_id_fkey FOREIGN KEY (created_by_auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT rendez_vous_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id),
  CONSTRAINT rendez_vous_etat_des_lieux_id_fkey FOREIGN KEY (etat_des_lieux_id) REFERENCES public.etat_des_lieux(id),
  CONSTRAINT fk_rendez_vous_etat_des_lieux FOREIGN KEY (etat_des_lieux_id) REFERENCES public.etat_des_lieux(id),
  CONSTRAINT rendez_vous_updated_by_auth_user_id_fkey FOREIGN KEY (updated_by_auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT rendez_vous_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT rendez_vous_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id)
);
CREATE TABLE public.stripe_customers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  stripe_customer_id text NOT NULL UNIQUE,
  email text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  employe_id uuid,
  CONSTRAINT stripe_customers_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_customers_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id),
  CONSTRAINT stripe_customers_auth_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.stripe_webhooks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  stripe_event_id text NOT NULL UNIQUE,
  event_type text NOT NULL,
  processed boolean DEFAULT false,
  data jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  user_id uuid,
  CONSTRAINT stripe_webhooks_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_webhooks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.subscription_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  stripe_price_id text NOT NULL UNIQUE,
  stripe_product_id text NOT NULL,
  amount integer NOT NULL,
  currency text NOT NULL DEFAULT 'eur'::text,
  interval text NOT NULL CHECK ("interval" = ANY (ARRAY['month'::text, 'year'::text])),
  interval_count integer NOT NULL DEFAULT 1,
  features jsonb DEFAULT '[]'::jsonb,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  employe_id uuid,
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_plans_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id),
  CONSTRAINT subscription_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  organisation_id uuid,
  stripe_subscription_id text NOT NULL UNIQUE,
  stripe_customer_id text NOT NULL,
  plan_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'canceled'::text, 'incomplete'::text, 'incomplete_expired'::text, 'past_due'::text, 'trialing'::text, 'unpaid'::text])),
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean DEFAULT false,
  canceled_at timestamp with time zone,
  trial_start timestamp with time zone,
  trial_end timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  employe_id uuid,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id),
  CONSTRAINT subscriptions_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.organisations(id),
  CONSTRAINT subscriptions_employe_id_fkey FOREIGN KEY (employe_id) REFERENCES public.employes(id),
  CONSTRAINT subscriptions_auth_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);